<?php
/*
Plugin Name: Author Order By Login Name
Version: 0.4
Description: Sort author options in alphabetical order of login name.
Plugin URI: https://github.com/magazine-k/author-order-by-login-name
Author: magazine-k.jp
Author URI: http://magazine-k.jp
*/
function magk_dropdown_users( $args = '' ) {
	$defaults = array(
		'show_option_all' => '', 'show_option_none' => '', 'hide_if_only_one_author' => '',
		'orderby' => 'slug', 'order' => 'ASC',
		'include' => '', 'exclude' => '', 'multi' => 0,
		'show' => 'display_name', 'echo' => 1,
		'selected' => 0, 'name' => 'post_author_override', 'class' => '', 'id' => '',
		'blog_id' => $GLOBALS['blog_id'], 'who' => 'authors', 'include_selected' => false,
		'option_none_value' => -1
	);
	$defaults['selected'] = is_author() ? get_query_var( 'author' ) : 0;
	$r = wp_parse_args( $args, $defaults );
	$show = $r['show'];
	$show_option_all = $r['show_option_all'];
	$show_option_none = $r['show_option_none'];
	$option_none_value = $r['option_none_value'];
	$query_args = wp_array_slice_assoc( $r, array( 'blog_id', 'include', 'exclude', 'orderby', 'order', 'who' ) );
	$query_args['fields'] = array( 'ID', 'user_login', $show );
	$users = get_users( $query_args );
	$output = '';
	if ( ! empty( $users ) && ( empty( $r['hide_if_only_one_author'] ) || count( $users ) > 1 ) ) {
		$name = esc_attr( $r['name'] );
		if ( $r['multi'] && ! $r['id'] ) {
			$id = '';
		} else {
			$id = $r['id'] ? " id='" . esc_attr( $r['id'] ) . "'" : " id='$name'";
		}
		$output = "<select name='{$name}'{$id} class='" . $r['class'] . "'>\n";
		if ( $show_option_all ) {
			$output .= "\t<option value='0'>$show_option_all</option>\n";
		}
		if ( $show_option_none ) {
			$_selected = selected( $option_none_value, $r['selected'], false );
			$output .= "\t<option value='" . esc_attr( $option_none_value ) . "'$_selected>$show_option_none</option>\n";
		}
		$found_selected = false;
		foreach ( (array) $users as $user ) {
			$user->ID = (int) $user->ID;
			$_selected = selected( $user->ID, $r['selected'], false );
			if ( $_selected ) {
				$found_selected = true;
			}
			$display = $user->user_login.' ('.$user->$show.')';
			$output .= "\t<option value='$user->ID'$_selected>" . esc_html( $display ) . "</option>\n";
		}
		if ( $r['include_selected'] && ! $found_selected && ( $r['selected'] > 0 ) ) {
			$user = get_userdata( $r['selected'] );
			$_selected = selected( $user->ID, $r['selected'], false );
			$display = ! empty( $user->$show ) ? $user->$show : '('. $user->user_login . ')';
			$output .= "\t<option value='$user->ID'$_selected>" . esc_html( $display ) . "</option>\n";
		}
		$output .= "</select>";
	}
	/**
	 * Filter the wp_dropdown_users() HTML output.
	 *
	 * @since 2.3.0
	 *
	 * @param string $output HTML output generated by wp_dropdown_users().
	 */
	$html = apply_filters( 'wp_dropdown_users', $output );
	if ( $r['echo'] ) {
		echo $html;
	}
	return $html;
}



// Replace Post Author from Standard Editor
function magk_post_author_meta_box($post) {

	global $user_ID;
?>
<label class="screen-reader-text" for="post_author_override"><?php _e( 'Authors (login name order mode):', 'author-order-by-login-name' ); ?></label>
<?php
	magk_dropdown_users( array(
		'selected' => empty($post->ID) ? $user_ID : $post->post_author,
		'include_selected' => true
	) );
}
add_action( 'add_meta_boxes_post',  'magk_add_meta_boxes' );
function magk_add_meta_boxes() {
    remove_meta_box( 'authordiv', 'post', 'core' );
    add_meta_box( 'authordiv', _e( 'Authors (login name order mode):', 'author-order-by-login-name' ), 'magk_post_author_meta_box', 'post', 'advanced', 'high' );
}
